services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - cache
      - postgres

  db:
    image: "mongo:4.4"
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]
    ports:
      - "27017:27017"

  cache:
    image: "redis:latest"
    ports:
      - "6379:6379"

  node:
    build:
      context: .
      dockerfile: ./node.dockerfile
    # image: "node:latest"
    working_dir: /app
    volumes:
      - .:/app
    command: npm start
    # command: ["tail", "-f", "/dev/null"]
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
    ports:
      - "3000:3000"

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sefaria
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/sefaria_data

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
      # - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - node

volumes:
  mongo-data:
  postgres-data:
